
swagger: '2.0'
info:
  title: Contact manager API
  version: 1.0.0
  description: API for searching, deleting, editing, and adding contacts. It also contains endpoints for creating an account and logging in.
host: group26.xyz
basePath: /LAMPAPI
schemes:
  - http
paths:
  /CreateAccount.php:
    post:
      summary: Creates Account
      parameters:
        - in: body
          name: input
          required: true
          schema:
            type: object
            required:
              - FirstName
              - LastName
              - Login
              - Password 
            properties:
              FirstName:
                type: string
              LastName:
                type: string
              Login:
                type: string
              Password:
                type: string
      responses:
        '200':
          description: Account created successfully
          schema:
            type: object
            properties:
              error:
                type: string
              message:
                type: string
  /Login.php:
    post:
      summary: Logs you into account
      parameters:
        - in: body
          name: input
          required: true
          schema:
            type: object
            required:
              - Login
              - Password 
            properties:
              Login:
                type: string
              Password:
                type: string
      responses:
        '200':
          description: Account created successfully
          schema:
            type: object
            properties:
              id:
                type: integer
              firstName:
                type: string
              lastName:
                type: string
              error:
                type: string
  /AddContact.php:
    post:
      summary: Logs you into account
      parameters:
        - in: body
          name: input
          required: true
          schema:
            type: object
            required:
              - FirstName
              - LastName
              - Phone
              - Email
              - UserID 
            properties:
              FirstName:
                type: string
              LastName:
                type: string
              Phone:
                type: string
              Email:
                type: string
              UserID:
                type: integer
      responses:
        '200':
          description: successfully added contact
          schema:
            type: object
            properties:
              error:
                type: string
              message:
                type: string
  /SearchContacts.php:
    post:
      summary: searchs for contacts
      parameters:
        - in: body
          name: input
          required: true
          schema:
            type: object
            required:
              - Search
              - UserID
              - PrevID
            properties:
              Search:
                type: string
              UserID:
                type: string
              PrevID:
                type: string
      responses:
        '200':
          description: successfully added contact
          schema:
            type: object
            properties:
              Results:
                type: array
                items:
                  type: object
                  properties:
                    FirstName:
                      type: string
                    LastName:
                      type: string
                    Phone:
                      type: string
                    Email:
                      type: string
                    ID:
                      type: integer
              Error:
                type: string
  /EditContact.php:
    post:
      summary: Edits a contact
      parameters:
        - in: body
          name: input
          required: true
          schema:
            type: object
            required:
              - FirstName
              - LastName
              - Phone
              - Email
              - UserID 
              - ID
            properties:
              FirstName:
                type: string
              LastName:
                type: string
              Phone:
                type: string
              Email:
                type: string
              UserID:
                type: integer
              ID:
                type: integer
      responses:
        '200':
          description: successfully added contact
          schema:
            type: object
            properties:
              error:
                type: string
              message:
                type: string
  /DeleteContact.php:
    post:
      summary: Edits a contact
      parameters:
        - in: body
          name: input
          required: true
          schema:
            type: object
            required:
              - ID
            properties:
              ID:
                type: integer
      responses:
        '200':
          description: successfully deleted contact
          schema:
            type: object
            properties:
              error:
                type: string
              message:
                type: string